# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(verbose_name='match date')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Sport')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='team0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team0', to='scoreboard.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='scoreboard.Team'),
        ),
    ]
