# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20170303_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='score0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='score1',
            field=models.IntegerField(default=0),
        ),
    ]
