# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_sport_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
