# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_auto_20170405_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
