# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0009_event_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='score0',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='score1',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
